---
# Default configuration
title: "evens.link"
baseURL: https://evens.link/fr
canonifyURLs: True
enableEmoji: True
enableGitInfo: True
defaultContentLanguage: fr
languageCode: fr
paginate: 10

copyright : "Copyright © 2016 – 2024 Evens SOLIGNAC. Tous droits réservés."

# Directories
archetypeDir: archetypes
contentDir: content
dataDir: data
publishDir: public
staticDir: static
layoutdir: layouts

languages:
  fr:
    title: "Evens SOLIGNAC"
    languageName: Français
    baseURL: https://evens.link/
    contentDir: content
    weight: 1
  en:
    title: "Evens SOLIGNAC — (English)"
    languageName: English
    baseURL: https://evens.link/en
    contentDir: content/en
    weight: 3

# Theme
theme: "hugo-split-theme"

blackfriday:
  hrefTargetBlank: true

# Params
params:
  author: "Evens SOLIGNAC"
  description: "Evens SOLIGNAC - evens.link"
  shareImage: "images/es.png"
  favicon: "favicon.ico"
  visual:
    image:
      enable: true
      file: "images/kBxyP2pgH75p1cKf.jpeg"
      position: "center center"
  custom:
    css:
      enable: true
  links:
    - list1:
        heading: '#THESLGCOMPANY'
        link:
          - text: GITHUB
            url: 'https://github.com/slgevens/'
          - text: "CV (FR) (PDF)"
            url: "misc/FvYVz4oI8A8dE1IFp.pdf"
          - text: "CV (EN) (PDF)"
            url: "misc/Eh3MAn8KZ5wyHv4G0.pdf"
    - list2:
        heading: '#LIVE'
        link:
          - text: NOSTRUM CARE
            url: 'https://www.nostrumcare.fr/'
          - text: MA WEB MUTUELLE
            url: 'https://apps.apple.com/us/app/mwm/id1593180602'
          - text: BESEDO
            url: 'https://besedo.com/'
