---
# Default configuration
title: "evens.link"
baseURL: https://evens.link/fr
canonifyURLs: True
enableEmoji: True
enableGitInfo: True
defaultContentLanguage: fr
languageCode: fr
paginate: 10

copyright : "Copyright © 2021 Evens SOLIGNAC. Tous droits réservés."

# Directories
archetypeDir: archetypes
contentDir: content
dataDir: data
publishDir: public
staticDir: static
layoutdir: layouts

languages:
  fr:
    title: "Evens SOLIGNAC"
    languageName: Français
    baseURL: https://evens.link/
    contentDir: content
    weight: 1
  es:
    title: "Evens SOLIGNAC — (Espanõl)"
    languageName: Espanõl
    baseURL: https://evens.link/es
    contentDir: content/es
    weight: 2
  en:
    title: "Evens SOLIGNAC — (English)"
    languageName: English
    baseURL: https://evens.link/en
    contentDir: content/en
    weight: 3

# Theme
theme: "hugo-split-theme"

blackfriday:
  hrefTargetBlank: true

# Params
params:
  author: "Evens SOLIGNAC"
  description: "Evens SOLIGNAC - evens.link"
  shareImage: "images/logo_v2-400.png"
  favicon: "favicon.ico"
  visual:
    image:
      enable: true
      file: "images/IMG_4070.jpg"
      position: "center center"
  custom:
    css:
      enable: true
  links:
    - list1:
        heading: '#THESLGCOMPANY'
        link:
          - text: '#THESLGSTORE'
            url: 'https:/theslgstore.com'
          - text: GITHUB
            url: 'https://github.com/slgevens/'
    - list2:
        heading: '#LIVE'
        link:
          - text: SABRINALOSTEO
            url: 'https://sabrinalosteo.paris'
          - text: NOSTRUMCARE
            url: 'https://www.nostrumcare.fr/'
